name: Dodaj galerię
description: Zgłoś nowy album Google Photos lub folder Google Drive do dodania na stronę
title: "Nowy album: "
labels: ["album-submission"]
body:
  - type: input
    id: url
    attributes:
      label: Link do albumu (Google Photos lub Google Drive)
      description: Udostępniony link, np. https://photos.app.goo.gl/XYZ lub https://drive.google.com/drive/folders/XYZ
      placeholder: https://photos.app.goo.gl/XYZ
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Własna nazwa (opcjonalnie)
      description: Podaj, jeśli tytuł albumu jest nieczytelny lub pusty
      placeholder: Wolin
    validations:
      required: false
  - type: input
    id: date
    attributes:
      label: Data
      description: Data albumu w formacie RRRR-MM-DD
      placeholder: "2024-08-03"
    validations:
      required: true
