/**
 * Defines the deliberately small, public-only offline contract used to generate the PWA worker.
 * Keeping the policy in TypeScript lets Node tests verify the browser-worker rules before build
 * generation turns them into a standalone JavaScript file.
 */
export const PWA_CACHE_PREFIX = 'kruki-pwa-';
// KRKG-0050 batch 5/6: raised from 100 KiB - style.css (a precached shell asset) was already at
// 102251 bytes before this batch's small, genuinely necessary .audyt-history-link addition (the
// "◷ Historia" deep-link style used site-wide, see style.css's own comment on it), leaving no
// realistic headroom for any future site-wide CSS addition either. 110 KiB keeps the same "small,
// reviewed shell" intent while giving a little real margin instead of sitting one class away from
// the ceiling again.
export const MAX_PRECACHE_BYTES = 110 * 1024;

/** The only files the worker may store in Cache Storage. */
export const PRECACHE_PATHS = [
  '/offline.html',
  '/style.css',
  '/favicon.png',
  '/manifest.webmanifest',
  '/pwa-register.js',
  '/pwa-icons/icon-192.png',
] as const;

/** Public documents that opt into PWA installation and offline fallback. */
export const PUBLIC_PWA_PATHS = new Set([
  '/',
  '/kontakt/',
  '/grafiki/',
  '/oferty/',
  '/nabor/',
  '/o-nas/',
  '/o-nas/nasze-osiagniecia/',
  '/poradnik-walki/',
  '/zasady-bractwa/',
  '/turniej/',
  '/turniej/en/',
  '/wojownicy/',
  '/wojownicy/blachowi/',
  '/wojownicy/emeryci/',
  '/wojownicy/kandydaci/',
  '/wojownicy/niewiasty/',
  '/publiczne-materialy/archiwalna-wersja-strony/',
]);

/** Paths whose documents and responses must never receive offline handling. */
export const GATED_PATH_PREFIXES = [
  '/admin/',
  '/galerie/',
  '/logowanie/',
  // KRKG-0046: session-gated self-service registration - same reasoning as /logowanie/ (auth
  // flow, not a public content page) even though it's reachable by non-members too.
  '/zgloszenie/',
  '/wojownicy/wrzuc/',
  // KRKG-0037: /profil/ replaces /wojownicy/wrzuc/ and carries the same personal-data/photo-
  // upload sensitivity (plus member profile fields wrzuc.js never had) - same exclusion.
  '/profil/',
  // The event roster/sign-up page (design.md §8, not built yet) - gated the same way since it
  // will hold personal/member data once it does anything beyond today's placeholder.
  '/lista-wyjazdowa/',
  // KRKG-0045: the member directory lists every group member's name/nickname/section/email -
  // the same personal-data sensitivity as /profil/ above.
  '/czlonkowie/',
  // KRKG-0050: the member-zone Historia page (public/audyt/) - authenticated audit history, same
  // sensitivity class as /profil//czlonkowie/ above. /admin/audyt/ needs no separate entry - it's
  // already covered by the existing '/admin/' prefix.
  '/audyt/',
] as const;

/** Returns whether a pathname belongs to the intentionally public PWA entry-point set. */
export function isEligiblePublicDocument(pathname: string): boolean {
  return PUBLIC_PWA_PATHS.has(pathname);
}

/** Returns whether a pathname is member-gated or otherwise excluded from PWA handling. */
export function isPwaExcludedPath(pathname: string): boolean {
  return GATED_PATH_PREFIXES.some(prefix => pathname === prefix.slice(0, -1) || pathname.startsWith(prefix));
}

/** Rejects any precache addition outside the reviewed, small shell allowlist. */
export function validatePrecacheAsset(pathname: string, byteLength: number): void {
  if (!PRECACHE_PATHS.includes(pathname as typeof PRECACHE_PATHS[number])) {
    throw new Error(`PWA precache path is not allowed: ${pathname}`);
  }
  if (byteLength > MAX_PRECACHE_BYTES) {
    throw new Error(`PWA precache asset exceeds ${MAX_PRECACHE_BYTES} bytes: ${pathname}`);
  }
}

/** Produces an owned Cache Storage name for a single static deployment. */
export function cacheNameForDeployment(identifier: string): string {
  return `${PWA_CACHE_PREFIX}${identifier}`;
}

/** Generates the standalone browser worker from the already reviewed policy constants. */
export function renderServiceWorker({
  cacheName,
  precachePaths,
}: {
  cacheName: string;
  precachePaths: readonly string[];
}): string {
  return `/* Generated by scripts/build-pwa.ts. Do not edit directly. */
const CACHE_NAME = ${JSON.stringify(cacheName)};
const CACHE_PREFIX = ${JSON.stringify(PWA_CACHE_PREFIX)};
const PRECACHE_PATHS = ${JSON.stringify(precachePaths)};
const PUBLIC_PWA_PATHS = new Set(${JSON.stringify([...PUBLIC_PWA_PATHS])});
const GATED_PATH_PREFIXES = ${JSON.stringify(GATED_PATH_PREFIXES)};

function isEligiblePublicDocument(pathname) {
  return PUBLIC_PWA_PATHS.has(pathname);
}

function isPwaExcludedPath(pathname) {
  return GATED_PATH_PREFIXES.some(prefix => pathname === prefix.slice(0, -1) || pathname.startsWith(prefix));
}

self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE_NAME).then(cache => cache.addAll(PRECACHE_PATHS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys
    .filter(key => key.startsWith(CACHE_PREFIX) && key !== CACHE_NAME)
    .map(key => caches.delete(key)))).then(() => self.clients.claim()));
});

self.addEventListener('fetch', event => {
  const { request } = event;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === 'navigate' && isEligiblePublicDocument(url.pathname) && !isPwaExcludedPath(url.pathname)) {
    event.respondWith(fetch(request).catch(() => caches.match('/offline.html')));
    return;
  }

  if (PRECACHE_PATHS.includes(url.pathname)) {
    event.respondWith(caches.match(request).then(cached => cached ?? fetch(request)));
  }
});
`;
}
