/**
 * Defines the deliberately small, public-only offline contract used to generate the PWA worker.
 * Keeping the policy in TypeScript lets Node tests verify the browser-worker rules before build
 * generation turns them into a standalone JavaScript file.
 */
export const PWA_CACHE_PREFIX = 'kruki-pwa-';
export const MAX_PRECACHE_BYTES = 100 * 1024;

/** The only files the worker may store in Cache Storage. */
export const PRECACHE_PATHS = [
  '/offline.html',
  '/style.css',
  '/favicon.png',
  '/manifest.webmanifest',
  '/pwa-register.js',
  '/pwa-icons/icon-192.png',
] as const;

/** Public documents that opt into PWA installation and offline fallback. */
export const PUBLIC_PWA_PATHS = new Set([
  '/',
  '/kontakt/',
  '/nabor/',
  '/o-nas/',
  '/o-nas/nasze-osiagniecia/',
  '/poradnik-walki/',
  '/zasady-bractwa/',
  '/turniej/',
  '/turniej/en/',
  '/wojownicy/',
  '/wojownicy/blachowi/',
  '/wojownicy/emeryci/',
  '/wojownicy/kandydaci/',
  '/wojownicy/niewiasty/',
  '/publiczne-materialy/archiwalna-wersja-strony/',
]);

/** Paths whose documents and responses must never receive offline handling. */
export const GATED_PATH_PREFIXES = ['/admin/', '/galerie/', '/logowanie/', '/wojownicy/wrzuc/'] as const;

/** Returns whether a pathname belongs to the intentionally public PWA entry-point set. */
export function isEligiblePublicDocument(pathname: string): boolean {
  return PUBLIC_PWA_PATHS.has(pathname);
}

/** Returns whether a pathname is member-gated or otherwise excluded from PWA handling. */
export function isPwaExcludedPath(pathname: string): boolean {
  return GATED_PATH_PREFIXES.some(prefix => pathname === prefix.slice(0, -1) || pathname.startsWith(prefix));
}

/** Rejects any precache addition outside the reviewed, small shell allowlist. */
export function validatePrecacheAsset(pathname: string, byteLength: number): void {
  if (!PRECACHE_PATHS.includes(pathname as typeof PRECACHE_PATHS[number])) {
    throw new Error(`PWA precache path is not allowed: ${pathname}`);
  }
  if (byteLength > MAX_PRECACHE_BYTES) {
    throw new Error(`PWA precache asset exceeds ${MAX_PRECACHE_BYTES} bytes: ${pathname}`);
  }
}

/** Produces an owned Cache Storage name for a single static deployment. */
export function cacheNameForDeployment(identifier: string): string {
  return `${PWA_CACHE_PREFIX}${identifier}`;
}

/** Generates the standalone browser worker from the already reviewed policy constants. */
export function renderServiceWorker({
  cacheName,
  precachePaths,
}: {
  cacheName: string;
  precachePaths: readonly string[];
}): string {
  return `/* Generated by scripts/build-pwa.ts. Do not edit directly. */
const CACHE_NAME = ${JSON.stringify(cacheName)};
const CACHE_PREFIX = ${JSON.stringify(PWA_CACHE_PREFIX)};
const PRECACHE_PATHS = ${JSON.stringify(precachePaths)};
const PUBLIC_PWA_PATHS = new Set(${JSON.stringify([...PUBLIC_PWA_PATHS])});
const GATED_PATH_PREFIXES = ${JSON.stringify(GATED_PATH_PREFIXES)};

function isEligiblePublicDocument(pathname) {
  return PUBLIC_PWA_PATHS.has(pathname);
}

function isPwaExcludedPath(pathname) {
  return GATED_PATH_PREFIXES.some(prefix => pathname === prefix.slice(0, -1) || pathname.startsWith(prefix));
}

self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE_NAME).then(cache => cache.addAll(PRECACHE_PATHS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys
    .filter(key => key.startsWith(CACHE_PREFIX) && key !== CACHE_NAME)
    .map(key => caches.delete(key)))).then(() => self.clients.claim()));
});

self.addEventListener('fetch', event => {
  const { request } = event;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === 'navigate' && isEligiblePublicDocument(url.pathname) && !isPwaExcludedPath(url.pathname)) {
    event.respondWith(fetch(request).catch(() => caches.match('/offline.html')));
    return;
  }

  if (PRECACHE_PATHS.includes(url.pathname)) {
    event.respondWith(caches.match(request).then(cached => cached ?? fetch(request)));
  }
});
`;
}
